### ISSUE TITLE
Doent work for ember-cli: 2.13.2

### ISSUE THREAD

**Issue by kuldeeptp** [ahmadsoe/ember-highcharts#123]
Hi ,
   I am passing param as below but it fails on ember 2.13.2 version
but the same code works on Ember 2.12.1

{{high-charts  chartOptions=chartOptions content=mydata }}
where "mydata=[{data:[[100,-12778],[105,-12778],[110,-12778]]}] 

Below is the error
`
_ember.debug.js:19818 Error: Assertion Failed: You must use Ember.set() to set the `data` property (of [object Object]) to `100,-12778,105,-12778,110,-12778,112,-12778,113,-12778,114,-12778,115,-12778,116,-12778,117,-12778,118,-12778,119,-12778,120,-12778,121,-12778,122,-12778,123,-12778,124,-12778,125,-12778,126,-12778,127,-12778,128,-12778,129,-12778,130,-12778,131,-12778,132,-12778,133,-12778,134,-12778,135,-12778,136,-12778,139,-12778,140,-12778,141,-12778,145,-12778,150,-12778`.`_

**Comment by ldong** [comment]
It breaks on 2.14 too. Similar method `setData`

**Comment by kuldeeptp** [comment]
I managed to make it work
Problem was with the data type converting string type to integer

and it started working.

**Comment by ahmadsoe** [comment]
> and it started working.

Closing this...
